#!/usr/bin/env python2
import os, textwrap

text = raw_input("Text: ")
tw = textwrap.TextWrapper(width=30)
newtext = u"\n".join([a.replace("\\n", "\n") for a in tw.wrap(text)])

os.system("convert -size 1920x1080 canvas:\"rgb(149, 1, 1)\" \
-font DejaVu-Sans-Bold -pointsize 100 -gravity center -stroke none \
-fill white -annotate 0 \"{}\" -size 1920x1080 \"{}.png\"".format(newtext,
  "".join([c for c in text.replace(" ", "-") if c.isalpha() or c.isdigit() or c in ["-", "_"]])))

