#!/usr/bin/env python2
from flask import Flask, render_template, request, make_response
import os
import textwrap

from config import SECRET

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/process/', methods=['GET', 'POST'])
def process():
    if not 'whoa' in request.args:
        return "lol"
    if not request.args['whoa'] == SECRET:
        return "lol"
    text = request.args['text']
    tw = textwrap.TextWrapper(width=30)
    newtext = u"\n".join([a.replace("\\n", "\n") for a in tw.wrap(text)])
    os.system("convert -size 1920x1080 canvas:\"rgb(149, 1, 1)\" \
-font DejaVu-Sans-Bold -pointsize 100 -gravity center -stroke none \
-fill white -annotate 0 \"{}\" -size 1920x1080 \"{}.png\"".format(newtext,
  "".join([c for c in text.replace(" ", "-") if c.isalpha() or c.isdigit() or c in ["-", "_"]])))
    os.system("screen -S tehpix -X stuff './viewimage *.*\n'")
    return render_template("done.html")

if __name__ == "__main__":
    app.run(debug=False, host="0.0.0.0", port=2345)
